# Generated by Django 5.1.15 on 2026-09-20 18:35

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Account created'), ('USER_UPDATE', 'Account updated'), ('DEVICE_ENROL', 'Device enrolled'), ('DEVICE_REVOKE', 'Device revoked'), ('SENSOR_CREATE', 'Sensor created'), ('SENSOR_UPDATE', 'Sensor updated'), ('SENSOR_DELETE', 'Sensor deleted'), ('ALERT_ACKNOWLEDGE', 'Alert acknowledged'), ('ZONE_CREATE', 'Zone created'), ('ZONE_UPDATE', 'Zone updated'), ('ZONE_DELETE', 'Zone deleted')], db_index=True, max_length=40)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('DENIED', 'Denied'), ('FAILURE', 'Failure')], max_length=10)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=512)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context recorded by the view', validators=[core.validators.JSONSchemaValidator('audit.metadata'), core.validators.MaxJSONSizeValidator(8192)])),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit entry',
                'verbose_name_plural': 'Audit entries',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='audit_log_actor_i_485cf7_idx'), models.Index(fields=['action', '-timestamp'], name='audit_log_action_cf8063_idx'), models.Index(fields=['outcome', '-timestamp'], name='audit_log_outcome_a6b6ad_idx')],
            },
        ),
    ]
