# Generated by Django 5.1.15 on 2026-09-04 22:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('object_class', models.CharField(help_text='person, vehicle, animal, unknown', max_length=30)),
                ('confidence', models.FloatField()),
                ('bounding_box', models.JSONField(help_text='[x1, y1, x2, y2], normalised to 0-1 like ZonePerimeter.polygon')),
                ('frame_path', models.CharField(help_text='Object-store key for the frame, so the event can be reviewed against the image', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_events', to='sensors.sensor')),
            ],
            options={
                'db_table': 'zone_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
