# Generated by Django 5.1.15 on 2026-09-04 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intelligence', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneevent',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='zones.zone'),
        ),
        migrations.AddIndex(
            model_name='zoneevent',
            index=models.Index(fields=['zone', '-timestamp'], name='zone_events_zone_id_3115e2_idx'),
        ),
        migrations.AddIndex(
            model_name='zoneevent',
            index=models.Index(fields=['object_class', '-timestamp'], name='zone_events_object__8ccd76_idx'),
        ),
        migrations.AddIndex(
            model_name='zoneevent',
            index=models.Index(fields=['camera', '-timestamp'], name='zone_events_camera__968dd5_idx'),
        ),
    ]
