# Generated by Django 5.1.14 on 2025-11-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('INTRUSION', 'Intrusion Detected'), ('MOTION', 'Motion Detected'), ('DOOR_OPEN', 'Door Opened'), ('WINDOW_OPEN', 'Window Opened'), ('GLASS_BREAK', 'Glass Break Detected'), ('SMOKE', 'Smoke Detected'), ('CO', 'Carbon Monoxide Detected'), ('WATER_LEAK', 'Water Leak Detected'), ('TEMPERATURE', 'Temperature Anomaly'), ('SYSTEM', 'System Alert'), ('CUSTOM', 'Custom Alert')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional alert context and data')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
