# Generated by Django 5.1.14 on 2025-11-27 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='sensor',
            field=models.ForeignKey(blank=True, help_text='Sensor that triggered the alert (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.sensor'),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(help_text='User who owns this alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', '-timestamp'], name='alerts_user_id_99b1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', '-timestamp'], name='alerts_severit_5781a0_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['acknowledged'], name='alerts_acknowl_046d76_idx'),
        ),
    ]
