# Generated by Django 5.1.15 on 2026-09-04 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zone this alert relates to (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='zones.zone'),
        ),
    ]
