# Generated by Django 5.1.15 on 2026-09-20 18:28

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Additional alert context and data', validators=[core.validators.JSONSchemaValidator('alert.metadata'), core.validators.MaxJSONSizeValidator(16384)]),
        ),
    ]
