# Generated by Django 5.1.14 on 2025-11-27 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable sensor name', max_length=255)),
                ('sensor_type', models.CharField(choices=[('CAMERA', 'Camera'), ('DOOR_CONTACT', 'Door Contact'), ('WINDOW_CONTACT', 'Window Contact'), ('GLASS_BREAK', 'Glass Break Sensor'), ('MOTION', 'Motion Detector'), ('SMOKE', 'Smoke Detector'), ('CO', 'Carbon Monoxide Detector'), ('WATER_LEAK', 'Water Leak Sensor'), ('TEMPERATURE', 'Temperature Sensor'), ('CUSTOM', 'Custom Sensor')], max_length=50)),
                ('location', models.CharField(help_text='Physical location of the sensor', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error')], default='ACTIVE', max_length=20)),
                ('handler_class', models.CharField(blank=True, help_text='Python path to the sensor handler class', max_length=255, null=True)),
                ('connection_config', models.JSONField(default=dict, help_text='Connection details (IP, port, credentials, etc.)')),
                ('metadata', models.JSONField(default=dict, help_text='Additional sensor metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'db_table': 'sensors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('value', models.JSONField(help_text='Sensor reading value (format depends on sensor type)')),
                ('reading_type', models.CharField(blank=True, help_text='Type of reading (e.g., motion_detected, temperature, image)', max_length=100, null=True)),
                ('processed', models.BooleanField(default=False, help_text='Whether this reading has been processed for threat detection')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'db_table': 'sensor_readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='sensor_read_sensor__ecf3b4_idx'), models.Index(fields=['processed'], name='sensor_read_process_92d7a6_idx')],
            },
        ),
    ]
