# Generated by Django 5.1.15 on 2026-09-20 18:28

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensor_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='connection_config',
            field=models.JSONField(default=dict, help_text='Connection details (IP, port, credentials, etc.)', validators=[core.validators.JSONSchemaValidator('sensor.connection_config'), core.validators.MaxJSONSizeValidator(16384)]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Additional sensor metadata', validators=[core.validators.JSONSchemaValidator('sensor.metadata'), core.validators.MaxJSONSizeValidator(16384)]),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='value',
            field=models.JSONField(help_text='Sensor reading value (format depends on sensor type)', validators=[core.validators.JSONSchemaValidator('sensor_reading.value'), core.validators.MaxJSONSizeValidator(65536)]),
        ),
    ]
