# Generated by Django 5.1.15 on 2026-09-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensor_connection_config_alter_sensor_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='public_key',
            field=models.CharField(blank=True, default='', help_text="Base64 Ed25519 public key (32 raw bytes) used to verify this sensor's readings. Empty means readings are unsigned.", max_length=64),
        ),
        migrations.AddField(
            model_name='sensor',
            name='require_signature',
            field=models.BooleanField(default=False, help_text="Refuse readings that are not signed by this sensor's key. Leave off while rolling signing out, then turn on to enforce."),
        ),
    ]
