# Generated by Django 5.1.15 on 2026-09-04 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(choices=[('ENTRY', 'Entry'), ('HALLWAY', 'Hallway'), ('PERIMETER', 'Perimeter'), ('RESTRICTED', 'Restricted'), ('COMMON', 'Common')], max_length=20)),
                ('expected_traffic', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('NONE', 'None')], default='LOW', max_length=10)),
                ('active_hours_start', models.TimeField(blank=True, help_text='When this zone is normally occupied', null=True)),
                ('active_hours_end', models.TimeField(blank=True, null=True)),
                ('known_regulars', models.JSONField(blank=True, default=list, help_text='Expected visitor categories, e.g. ["household", "delivery"]')),
                ('context', models.TextField(blank=True, help_text="Free-text description of the zone, in plain language. This is fed to the AI analysis layer, so physical detail that a model could not infer from pixels belongs here — for example: 'Back patio. The neighbour's cat sets off motion constantly. The gate has no lock.'")),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZoneRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('ALERT_UNKNOWN_PERSON', 'Alert on unknown person'), ('ALERT_AFTER_HOURS', 'Alert outside active hours'), ('ALERT_DWELL_TIME', 'Alert on dwell time'), ('ALERT_ZONE_TRANSITION', 'Alert on zone transition'), ('SUPPRESS_WINDOW', 'Suppress alerts in a window'), ('CUSTOM', 'Custom')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Rule-specific, e.g. {"dwell_threshold_seconds": 30}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='zones.zone')),
            ],
            options={
                'db_table': 'zone_rules',
                'ordering': ['zone', 'rule_type'],
            },
        ),
        migrations.CreateModel(
            name='ZoneAdjacency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('learned_transit_seconds', models.FloatField(blank=True, help_text='Observed median transit time, learned by the pipeline', null=True)),
                ('transit_sample_count', models.IntegerField(default=0)),
                ('manually_configured', models.BooleanField(default=False, help_text='Set when a person configured this edge; learning must not overwrite it')),
                ('from_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='zones.zone')),
                ('to_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='zones.zone')),
            ],
            options={
                'verbose_name_plural': 'zone adjacencies',
                'db_table': 'zone_adjacency',
                'unique_together': {('from_zone', 'to_zone')},
            },
        ),
        migrations.CreateModel(
            name='ZonePerimeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('polygon', models.JSONField(help_text='[[x1, y1], [x2, y2], ...] with each value normalised to 0-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(limit_choices_to={'sensor_type': 'CAMERA'}, on_delete=django.db.models.deletion.CASCADE, related_name='zone_perimeters', to='sensors.sensor')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perimeters', to='zones.zone')),
            ],
            options={
                'db_table': 'zone_perimeters',
                'unique_together': {('zone', 'camera')},
            },
        ),
    ]
